@extends('layout')
@section('content')
<div class="legal-header" style="background-image: url({{ asset('img/privacy.png') }})">
  <h1>Privacy Policy</h1>
</div>
<div class="legal-copy container">
    <p>Tix4Cause Privacy Policy</p>
    <p><strong>Effective as of November 1, 2018</strong></p>
    <p>At tix4cause.com, a website operated by Tix 4 Cause, LLC (Tix4Cause), we are committed to respecting people's privacy online. We are also committed to providing you with the very best experience we can on our website. In order to do so, we may gather certain personal information about you. Please read the following policy to understand how your personal information will be treated as you make full use of our website. By using tix4cause.com, you consent to the collection and use of your information by tix4cause as described in this Policy, and you signify your agreement to this Privacy Policy.</p>
    <p><strong>What information does Tix4Cause collect?</strong></p>
    <p>When you visit tix4cause.com, we collect some basic information that does not identify individual users. This includes which pages are visited and any feedback from our visitors. We then aggregate this information with other pieces of information to improve our site and make sure your experience on the site is as valuable and efficient as possible.</p>
    <p>When you register for the Tix4Cause service, we collect personal information such as name, age, address, phone and email in order to set up your account and fulfill your orders.  In addition to the information we collect upon your initial registration with tix4cause.com, we may ask you for personal information at other times, including, but not limited to, when you enter promotions or contests, when you purchase certificates, receive vouchers, and when you respond to a survey.</p>
    <p>We may also collect and accumulate anonymous data which will help us understand and analyze the Internet experience of our website users. For instance, we may accumulate visitor data relating to referring domain names, the type of browsers used, operating system software, screen resolutions, color capabilities, browser plug-ins, language settings, cookie preferences, search engine keywords and JavaScript enablement.</p>
    <p>We also collect IP addresses for system administration and to report aggregate information to any charities or sponsors. While an IP address does not identify an individual by name, it may, with the cooperation of the ISP, be used to locate and identify an individual. Your IP address can, however, reveal what geographic area you are connecting from, or which ISP you are using. Finally, other websites you visit have IP addresses, and we may collect the IP addresses of those websites and their pages.</p>
    <p>Upon canceling your Tix4Cause account, you have the right to request deletion of your account information, subject to our need to keep appropriate archives for our business operations.</p>
    <p>If/when applicable, tix4cause.com users can invite friends to visit tix4cause.com by sending invitation emails via our automated invitation system. Tix4Cause stores the email addresses that you provide to send reminders of the invitations.   
    <p><strong>What do we do with the information we collect?</strong></p>
    <p>1. It is used to set up and maintain your tix4cause.com account and to fulfill any orders. If you provide us with your mobile phone information, we may use such information to communicate with you regarding tix4cause.com by SMS, MMS, text message or other electronic means to a mobile device.</p>
    <p>2. We provide you with information about any order (such as whether your order has been received, processed, or shipped). We save the information about services you subscribe to and products you purchased to provide you with the best possible customer service and the most up-to-date information about your order.</p>
    <p>3. Your phone number may be used in the event that our customer service representatives need to contact you and cannot reach you by email.</p>
    
    <p>4. Credit card information is used to bill you for products you have ordered and to track sales.</p>
    
    <p>5. If you are a ticket donor, your name, address, and email address will be given to the entity you select to benefit from the sale of your donated tickets. This information must be given to the entity so that, when applicable, you can receive a donation acknowledgment letter recognizing your ticket donation and which may be used as a receipt for your charitable deduction.</p>
    
    <p>6. If you purchase a certificate, purchase information, including your name and email address, will be provided to the merchant whose certificate you purchased.</p>
    
    <p>7. Your personal information will never be sold to any other website owner or merchant. We hate junk mail as much as you. This is why we will only send you email about items that we feel you should know about. This includes special promotional items that tix4cause endorses, membership changes, terms and conditions changes, holiday cards, and the latest happenings on tix4cause.com. When we send you emails that include a link to the tix4cause.com, that link may contain an alphanumeric identifier that allows us to identify the person to whom we sent the message so that we can personalize our content for that individual. </p>
    
    <p><strong>Email Opt-out</strong></p>
    <p>Users who no longer wish to receive our email updates or other notifications may opt-out of receiving these communications by following the instructions contained in the applicable email or by logging-in and changing their account settings. </p>
    <p><strong>Credit Card Processing</strong></p>
    <p>Credit card security is an important aspect of the online experience. Credit card transactions are handled by a third-party processor that receives credit card numbers and other personally identifying information only to verify credit card accounts and process transactions. </p>
    <p><strong>With whom do we share your information and for what purpose?</strong></p>
    <p>We do not sell, rent, or trade any personally identifying information with others. However, if you are a ticket donor, we will provide your personal information (but not your credit card information) to the organization that is the beneficiary of your tix4cause donation. In addition, when one or more of our business partners co-sponsor a service, promotion and/or contest, we may share with the co-sponsor(s) some or all of the information collected in connection with such service, promotion or contest. If we intend to share such information, you will be notified prior to the collection of that information. If you do not want your information to be shared, you will be able to choose not to allow the transfer by not using or signing up for that particular service, promotion, or contest.</p>
    <p>We may also share aggregate user information in a non-personally identifiable manner with advertisers and other third parties in order to present to users more targeted advertising, products and services. </p>
    <p>We may contract with third parties to conduct research and marketing on our behalf. Such third parties will be fully bound by an obligation of confidentiality and may not use any personally-identifiable information provided by us other than as expressly instructed by us and in strict compliance with the terms of this Privacy Policy.</p>
    <p><strong>What information do parties other than Tix4Cause collect?</strong></p>
    <p>Some entities that may have links on our site may collect personally identifying information about you when you access or utilize those links. We do not control the collection or use of such information, and the practices of those advertisers and websites are not covered by this Privacy Policy.</p>
    <p>It is important to note that those entities may not follow the same privacy policies as Tix4Cause. For instance, if you click on an advertisement on tix4cause.com, you may be taken away from tix4cause.com to an entirely different site. These links can also be from advertisers, content providers and/or partners who may use tix4cause's logo and/or style as a result of a co-branding agreement yet they may still not follow the same privacy policies as tix4cause.</p>
    <p><strong>What are cookies and web beacons and how do we use them?</strong></p>
    <p>Our site may use cookies and web beacons to speed navigation, keep track of items, and provide you with custom-tailored services. A web beacon is an embedded GIF file that specifically helps us track whether you have viewed a specific piece of content. We also use cookies to remember information you gave us so you don't have to re-enter it each time you visit the site. By showing us how and when visitors use the site, cookies and web beacons help us see which site areas and content are popular and which are not. Some advertisers or websites that have links on our site may also use their own cookies. </p>
    <p>Most browsers are initially set to accept cookies. If you'd prefer, you can set yours to refuse cookies. You will not be able to use our service if you turn off the cookies option.</p>
    <p><strong>Security</strong></p>
    <p>Tix4Cause member accounts are secured by member-created passwords. In addition, we use commercially reasonable measures to protect member information that is stored within our database, and we restrict access to member information to those employees who need access to perform their job functions, such as our customer service personnel and technical staff.  We use Secured Sockets Layer (SSL) for secure transmissions. SSL applies encryption between two communicating applications, such as your PC and the server. Your name, other personal information, and all credit cards and other payment information that you transmit to us will be protected by 128-bit encryption technology, provided your browser is properly configured and your computer is operating properly. The SSL technology requires that you have a reasonably current browser that is capable of supporting 128-bit encryption. Current browsers such as these will activate the appropriate security features when you enter an online transaction through this site. Furthermore, we take reasonable measures to maintain the confidentiality of credit cards, debit cards, charge cards, and other access numbers under our control. Card numbers are stored for the duration of the transaction, and then deleted. </p>
    <p>However, please note that we cannot guarantee the security of member account information. Unauthorized entry or use, hardware or software failure, and other factors may compromise the security of our member information at any time.</p>
    <p><strong>COPPA compliance</strong></p>
    <p>We have designed this privacy policy in order to comply with the Children's Online Privacy Protection Act (&quot;COPPA&quot;). We will never knowingly collect any personal information about children under the age of 13. If we obtain actual knowledge that we have collected personal information about a child under the age of 13, that information will be immediately deleted from our database. Because we do not collect such information, we have no such information to use or to disclose to third parties.</p>
    <p><strong>Business transitions</strong></p>  
    <p>In the event Tix4Cause goes through a business transition, such as a merger, acquisition by another company or sale of a portion of its assets, users' personal information will, in most instances, be part of the assets transferred. California User Consumer Rights</p>
    <p>In accordance with California Civil Code Sec. 1789.3, once per calendar year California resident users have the right to receive: information (names and addresses) identifying any third party(ies) to whom we may have disclosed, within the preceding calendar year, certain of your personal information for that third party's direct marketing purposes as well as a description of the categories of personal information disclosed, as required under this law. To request such information, please email us at: customersupport@tix4cause.com or write to us at:</p>
    
    <p>Tix 4 Cause, LLC</p>
    <p>P.O. Box 4553</p> 
    <p>Naperville, IL 60567</p>
    <p>If you are a California resident under the age of 18 and have a registered account on our website, California Business and Professions Code Section 22581 permits you to request and obtain removal of content or information you have publicly posted. To make such a request, please send an email with a detailed description of the specific content or information to customersupport@tix4cause.com. Please be aware that such a request does not ensure complete or comprehensive removal of the content or information you have posted and that there may be circumstances in which the law does not require or allow removal even if requested.</p>
    <p><strong>Children's Privacy</strong></p>
    <p>Tix4Cause is not intended to be used by individuals under the age of 16. We do not knowingly request or collect personal information from any person under 16 years of age without prior verifiable parental consent. If you believe that your child under the age of 16 has submitted personal information to us in connection with our website, and without prior verifiable parental consent, please email us at customersupport@tix4cause.com so that we can take steps to delete the personal information that he/she provided as required in accordance with applicable law.</p>
    <p><strong>Users Located Outside of the United States</strong></p>
    <p>We make an effort to protect the personal information of all users of tix4cause.com. If you are unsure whether this privacy policy is in conflict with the rules applicable where you are located, you should not submit your personal information to tix4cause.com. If you provide personal information through our website, you agree that the personal information will be transferred to and processed in the United States of America and any other country or jurisdiction at our sole discretion. The laws that apply to the use and protection of personal information in the United States or other countries or jurisdictions in which we transfer or process personal information may be different than the laws and protections in your country. Those who access or use our website from jurisdictions outside the United States do so at their own choice and risk and are solely responsible for compliance with local law. While we take certain steps to safeguard your personal information, please note that the United States has NOT been deemed by the European Commission to ensure an adequate level of protection for personal data. Accordingly, the level of safeguards and legal protections provided in the United States or other non-European countries from which you may access our website may not be as stringent as that under European Union privacy standards or the privacy laws of some other countries, possibly including your home jurisdiction.</p>
    <p><strong>European Residents</strong></p>
    <p>If you are a resident of the European Union, you may have certain rights under European data protection law with respect to your personal data, including the right to request access to correct, amend, delete, limit the use if, or withdraw your consent for the processing of your personal data. You may also have the right to receive a copy of your personal data in a commonly used and machine-readable format and to transmit such data to another controller. To request deletion of, access to, or to make changes to data, or to otherwise exercise any of your rights in this paragraph, please email us at customersupport@tix4cause.com. Please remember that if you delete or limit the use of your personal data, you may not be able to use the services provided through our website.</p>
    <p>Cooperation with law enforcement; fraud protection</p>
    <p>Tix4Cause fully cooperates with law enforcement agencies in identifying those who use our services for illegal activities. We reserve the right to disclose information about members who we believe are in violation of applicable laws or regulations, or as required to respond to a subpoena, court orders or other legal process requiring such disclosure. We also reserve the right to report to law enforcement agencies any activities that we reasonably believe to be unlawful and to exchange information with other companies and organizations for fraud protection. </p>
    <p><strong>Changes to our Privacy Policy</strong></p>
    <p>Use of information we collect is subject to the Privacy Policy in effect at the time such information is used or collected. From time to time, we may change our Privacy Policy and will notify you of those changes by email or post a notice on the tix4cause.com website. Users are bound by any changes to the Privacy Policy when they use tix4cause.com after such changes have been first posted. Please note that if you opt out of receiving legal notices from us, those legal notices will still govern your use of tix4cause.com, and you are responsible for reviewing such legal notices for changes, as posted on tix4cause.com.</p>
    <p>Any questions regarding our Privacy Policy should be directed to customersupport@tix4cause.com.   </p>
</div>
@endsection