@extends('layout')
@section('content')
<div class="legal-header" style="background-image: url({{ asset('img/terms.png') }})">
  <h1>Proprietary Sales Terms & Conditions</h1>
</div>
<div class="legal-copy container">
  <h2>Tix4Cause Online Proprietary Sales Terms & Conditions</h2>
  <p>These Sales Terms and Conditions ("Sales Terms") govern your purchases of donated tickets and event tickets and certificates (“Proprietary Tickets”) offered by our cause members through their use of the Tix4Cause platform.  These Sales Terms specifically DO NOT govern the purchase of any product from any of our ticket exchange partners. You will be required to review and accept the specific sales terms pertaining to the purchase of exchange tickets at the time of purchase.
      By using or visiting the Tix4Cause website, you expressly agree to abide and be bound by these Sales Terms, as well as all applicable laws, ordinances and regulations. You represent that you are legally able to enter into a binding contract. If you are under the age of 18, then you may only use this site or our customer call center in conjunction with, and under the supervision of, a parent or guardian.</p>
  <p>Below you will find the full Sales Terms, which include but are not limited to, the specific items below that we are highlighting for you:</p>
  <ul>
    <li>All orders for Proprietary Tickets placed on tix4cause.com center must be confirmed by Tix4Cause before being accepted.</li>
    <li>Ticket prices may be above or below the "face value" listed on the ticket and they may also bear the name of the ticket donor.</li>
    <li>Confirmed orders may be filled with comparable or upgraded tickets if the original tickets are no longer available.</li>
    <li>All sales are final; there are no cancellations, returns, or exchanges.</li>
    <li>If an event is canceled, you will be given a full refund. If an event is postponed or rescheduled, and the original tickets are valid for entry at the time of the rescheduled event, your order will not qualify for a refund.</li>
    <li>You will receive a full refund from the cause member offering the Proprietary Ticket in the unlikely event that you do not receive valid tickets in time for you to attend the event.</li>
  </ul>
  <p><strong>The Social Enterprise</strong></p>
  <p>Tix4Cause is a social enterprise. This means that we have created the technology and the business model that enables charitable organizations that join Tix4Cause as member (“Cause Members”) to receive donation of entertainment tickets and then in turn use our technology to sell these tickets in order to raise funds to support their mission. Tix4Cause does not own or control any of the tickets offered on its website. The participating Cause Member receives 100% of the ticket purchase price for all Proprietary Tickets it posts on our website. For all exchange ticket purchases, Tix4Cause donates 50% of what it earns to the purchaser’s charity of choice. Tix4Cause ensures that every transaction offered on or through its website benefits a cause.</p>
  <p><strong>Ticket Listings</strong></p>
  <p>Buyers may search tix4cause.com for a specific artist or team, event date or other search category. Each listing contains the event name, date, seat location, and price per ticket. Please note, the ticket price may be higher than the “face value” that appears on the ticket. The notes section of the listing, if present, highlights special characteristics of the tickets contained in the listing. Because you will have an opportunity to look at the tickets available for a particular event and determine which tickets to purchase, it is your responsibility to confirm any relevant details or ask questions prior to purchasing by contacting Tix4Cause for all Proprietary Ticket concerns. All exchange ticket concerns can be addressed by calling the number provided on the exchange ticket listing page PRIOR to purchase.</p>
  <p><strong>Selecting and Purchasing Proprietary Tickets</strong></p>
  <p>Once you identify the tickets you would like to purchase, and select them, you will be directed through the checkout process where you will enter your name and address, and provide payment information. You will also be able to review the ticket details, total order price, and service and delivery fees. The total order value will include a service and delivery fee that is added by Tix4Cause to the price of the tickets set by the cause member. The service fees cover the costs of keeping our social enterprise operating and the delivery fees cover the costs to deliver the tickets to you via the method selected by you in order to receive the tickets in time for the event.
      By placing an order for Proprietary Tickets, you authorize Tix4Cause on behalf of its Cause Member to charge your method of payment for the total order amount. Once the order is confirmed, you will receive notification that the tickets will be delivered. If you do not receive notification of ticket delivery, contact us at customersupport@tix4cause.com for assistance.
      </p>
  <p><strong>Payment of Proprietary Tickets</strong></p>
  <p>By placing your order for Proprietary Tickets, you authorize Tix4Cause on behalf of its Cause Member to charge your method of payment for the total amount, which includes the ticket price and service and delivery fees. We accept Visa, MasterCard, and American Express. In the event that you dispute a charge and it is determined that the charge was valid and not the result of credit card or other payment fraud, Tix4Cause on behalf of its Cause Member has the right to seek payment, including all associated fees, by whatever means necessary, including using collection agencies and legal proceedings.</p>
  <p><strong>Pricing Errors of Proprietary Tickets</strong></p>
  <p>A large volume of Proprietary Tickets can be listed and available on tix4cause.com by the Tix4Cause Cause Members. Tix4Cause works closely with its Cause Members to make every effort to prevent pricing errors. On rare occasions when pricing errors occur, neither Tix4Cause nor its Cause Member shall be liable to the customer for this error. For the avoidance of doubt, if a ticket is subject to a pricing error, the Cause Member may offer the tickets to you at the corrected price. If the corrected price is not acceptable to you, the cause member will allow you to cancel your order.</p>
  <p><strong>Delivery of Tickets</strong></p>
  <p>Tickets may be delivered via Mobile, Email, FedEx or Special Delivery for the charge stated during the checkout process. Some tickets are delivered by an alternative method which will be described at the time of checkout or in a subsequent email.  The Fed Ex delivery charge consists of the actual cost of delivery as well as a surcharge that covers the additional work required by Tix4Cause to prepare the tickets for shipment.</p>
  <p>Delivery will occur on or before the delivery date on the listing, regardless of delivery method. Special Delivery includes same day delivery and may include Will Call, onsite pick up at the venue, pick up from another designated location (typically within two (2) miles of the venue, if possible), or messenger service. The exact delivery location for Special Delivery orders will be designated in the ticket description.</p>
  <p>When tickets are shipped to you, it is your responsibility to confirm that the tickets delivered to you are consistent with the order you placed. You shall have forty-eight (48) hours from the time of delivery to report any inconsistencies between your order and the delivered tickets. Neither Tix4Cause nor its Cause Members shall be liable or responsible for any inconsistencies discovered after the 48 hour window has passed.</p>
  <p>Tickets are typically delivered per this schedule unless the delivery date in the listing is a date in the future:</p>
  <ul>
    <li>E-tickets – Within 1 business day or for day of events within a few minutes of placing your order.</li>
    <li>Shipped – Arrive in 1-3 business days from placing the order.</li>
    <li>Special Delivery – at least one (1) hour before the scheduled event.</li>
  </ul>
  <p><strong>Proprietary Ticket Holder Behavior Policy</strong></p>
  <p>Attendees to live events must abide by the rules and policies of the venue, promoter and anyone else responsible for the event. Failure to follow such rules and policies may lead to consequences against you or the seller or original ticket holder. If you or another person using the Proprietary Ticket you purchased from a Cause Member on tix4cause.com fails to abide by those rules and policies, you are responsible for all applicable fines and legal or other expenses associated therewith. If you are asked to leave the event or you miss part of the event due to suspected or confirmed inappropriate behavior, you will not qualify for a refund. Further, should any violation result in the loss of the ticket donor’s season ticket rights or right to use any other tickets at that venue, or the right to purchase other tickets from that venue, you shall be held liable for all reasonable costs, expenses and losses associated with said loss including, but not limited to, all direct, indirect, vicarious, consequential, exemplary, incidental, special or punitive damages, including lost profits.</p>
  <p><strong>All Proprietary Ticket Sales are Final</strong></p>
  <p>All such sales are final. No refunds will be given for any reason other than cancellation of the event or failure to timely deliver valid Proprietary Tickets. This policy is necessary because of our status as a social enterprise. We are all working together to make a difference for our Cause Members. These members depend upon these donations to support their missions. In addition there is not enough time or staff to investigate reasons for a refund. A buyer is welcomed to make a donation of their tickets to any Cause Member listed on Tix4Cause if, after purchase, the buyer decides not to attend or becomes unable to attend the event.</p>
  <p>If Tix4Cause, acting on behalf of its Cause Member, fails to deliver any Proprietary Tickets purchased, Tix4Cause’s sole obligation or liability shall be limited to refunding the buyer any payments made to Tix4Cause on behalf of the Cause Member under this Agreement. Tix4Cause reserves the right to cancel and refund the buyer's order at any time for any reason.</p>
  <p><strong>Cancelled and Postponed Events - Proprietary Tickets Only</strong></p>
  <p>Tix4Cause, on behalf of its Cause Members, will refund the Proprietary Ticket purchase price, including delivery charges, for canceled events. To qualify for a refund, the buyer must return their Proprietary Tickets to Tix4Cause within 2 weeks of notice from Tix4Cause that the event is deemed “Cancelled.” No refunds will be given without the original tickets, unless otherwise determined by the Cause Member, in its sole discretion. Postponed or rescheduled events will not be refunded.</p>
  <p>Event date, times, venue and subject matter may change. We are not always notified if a show is postponed, rescheduled or canceled. It is the buyer's responsibility to monitor the event and to confirm any changes to the event with the entity putting on the event. In certain instances, a venue, promoter, or any entity putting on the event will require a ticket holder to relocate his or her seat or otherwise change the seating configuration in a manner beyond a Cause Member’s or Tix4Cause’s control. Neither the Cause member nor Tix4Cause shall be held responsible for any such change and will not be obligated to provide a refund or any other compensation.</p>
  <p><strong>Denial of Admission - Proprietary Tickets Only</strong></p>
  <p>If you have difficulty gaining admission to an event, contact us immediately by calling 877.344.8384. If the issue you are experiencing is not resolved and you are denied admission, you must obtain proof from the venue verifying that you were denied entry and send that to Tix4Cause along with a statement describing the specific circumstances. Upon receipt of the evidence, Tix4Cause will conduct an investigation. During that investigation, we will review the proof you submit. In the event that Tix4Cause determines that you were indeed denied entry, at no fault of your own, you will receive a full refund of the cost of the ticket including all fees and shipping charges, as the sole remedy. If the investigation results in a finding that you either did not attempt to use your tickets, you were granted entry, or your claim that you were denied entry has been found to be false, you will not be refunded and you may be subject to the consequences described below.</p>
  <p><strong>Lost, Stolen, or Damaged Proprietary Tickets</strong></p>
  <p>Please keep your tickets in a safe place. Neither the Cause Member nor Tix4Cause shall be held responsible for lost, stolen, damaged or destroyed tickets. You will not receive a refund for your order if you cannot locate your tickets once they are delivered to you. Please note that direct sunlight or heat can damage certain types of tickets.</p>
  <p><strong>Privacy Policy – Proprietary Tickets Only</strong></p>
  <p>Tix4Cause uses your information only as described in its Privacy Policy.</p>
  <p><strong>Unlawful Activity; Acceptable Use</strong></p>
  <p>Tix4Cause prohibits the use of its website for unlawful conduct. All users must comply with all local, state, federal and international laws, ordinances and regulations. By using this site, you agree not to use any false personal information or use an invalid or unauthorized credit or debit card. You agree not to use or permit anyone to use information provided through tix4cause.com for any unlawful or unauthorized purpose.</p>
  <p>We are the sole interpreter of tix4cause’s intended and acceptable use. This website is a social enterprise and is intended to be used by Cause members, and donors and individuals and companies seeking to donate or buy tickets to support a Cause Member and to attend an event, and where appropriate receive a tax acknowledgement latter recognizing the ticket donation and for no other purpose.</p>
  <p><strong>Investigations and Consequences</strong></p>
  <p>Tix4Cause monitors compliance with these Sales Terms and investigates alleged violations and other complaints against users. This includes any attempt to defraud, or otherwise harm Tix4Cause or its Cause Members on the website. You are required to cooperate in such investigations including, but not limited to, providing any and all information requested.
      Following an investigation, or for any other reason, Tix4Cause may, without prior notice, enforce certain consequences for violations of the Sales Terms, attempts to harm Tix4cause or its Cause Members on the website, or failure to cooperate with an investigation. Such consequences include but are not limited to:
  </p>
  <ul>
    <li>Canceling confirmed orders</li>
    <li>Issuing a warning</li>
    <li>Suspending or terminating your account</li>
    <li>Denying access to the website</li>
    <li>Rejecting pending orders</li>
    <li>Blocking future transactions</li>
    <li>Taking legal action such as filing civil or criminal charges, or seeking an injunction.</li>
  </ul>
  <p>You agree that monetary damages may not provide a sufficient remedy to Tix4Cause or its Cause Members for violations of these Sales Terms and that the damages and harm caused by such violation may lead to impaired good will, lost sales and increased expenses that are difficult to calculate. Accordingly, you consent to injunctive or other equitable relief for such violations.
      Tix4Cause reserves the right to report to appropriate law enforcement authorities or other relevant third parties any activity that it believes, in its sole discretion, may in any way violate any local, state, federal or international law.
      </p>
  <p><strong>Intellectual Property Ownership</strong></p>
  <p>The site, including all site software, databases, trademarks, logos, service marks, proprietary information and materials (and any intellectual property and other rights relating thereto) is owned by Tix4Cause or its Cause Members and will remain the property of each. Users of this site acknowledge that they do not acquire any ownership rights by using the site. Users may not use any such materials or property in connection with any product or service that is not offered by Tix4Cause, in any manner that is likely to cause confusion with Tix4Cause’s business, or in any manner that disparages Tix4Cause or its Cause Partners. Nothing contained on the site should be construed as granting, by implication, estoppel or otherwise, any license or right to use any such materials or propriety without the express written permission of Tix4Cause or, where applicable, its Cause Members.</p>
  <p><strong>Indemnification</strong></p>
  <p>You agree to indemnify, defend and hold Tix4Cause and where applicable,  its Cause Members,  its parents, affiliates, licensors, suppliers, advertisers and sponsors, and their respective employees, consultants, agents and other representatives ("Indemnified Parties") harmless from and against any and all claims, damages, losses, costs (including reasonable attorneys' fees) and other expenses that arise directly or indirectly out of or from: (a) your breach of any of these Sales Terms; (b) any allegation that any information you submit or transmit to the site infringe or otherwise violates the copyright, trademark, trade secret or other intellectual property or other rights of any third party; (c) any federal, state, or county tax obligation or amounts due or owing under any tax regulation, law, order or decree or any dispute concerning the tax status of Tix4Cause; and/or (d) your activities in connection with your use of this site.</p>
  <p><strong>Disclaimers and Limitations on Liability</strong></p>
  <p><strong>No Warranty</strong></p>
  <p>THE SITE, THE MATERIALS ON THE SITE AND ANY TICKET OR SERVICE OBTAINED THROUGH THE SITE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TIX4CAUSE DISCLAIMS, TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW, ALL WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO THE SITE, THE MATERIALS, AND ANY TICKETS OR SERVICE OBTAINED THROUGH THE SITE, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT OF THIRD PARTY RIGHTS, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING OR USAGE OF TRADE. TIX4CAUSE DOES NOT WARRANT THAT YOUR USE OF THE SITE WILL BE UNINTERRUPTED, ERROR-FREE OR SECURE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU ASSUME ALL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITE AND YOUR RELIANCE THEREON. TIX4CAUSE IS NOT RESPONSIBLE IN ANY WAY FOR THE ACCURACY OR SUITABILITY OF ANY PAYMENT OF TAXES TO ANY ENTITY ON YOUR BEHALF. YOUR USE OF THE SITE AND ANY MATERIALS PROVIDED THROUGH THE SITE ARE ENTIRELY AT YOUR OWN RISK. YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
  <p><strong>Limitation of Liability</strong></p>
  <p>NEITHER TIX4CAUSE NOR ANY OTHER INDEMNIFIED PARTY ARE OR WILL BE RESPONSIBLE OR LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS OR LOST PROFITS). UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO THE SITE, THE MATERIALS ON THE SITE OR ANY TICKET OR SERVICE OBTAINED THROUGH THE SITE. WITHOUT LIMITING THE FOREGOING, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT TIX4CAUSE AND ANY OTHER INDEMNIFIED PARTY SHALL HAVE NO LIABILITY OR RESPONSIBILITY WHATSOEVER FOR: (I) ANY ACTION OF ANOTHER USER TO THE SITE; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, WHETHER ARISING IN CONTRACT OR IN TORT, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, INCLUDING ANY CLAIM, CAUSE OF ACTION, OBLIGATION, LIABILITY, RIGHT, OR REMEDY WHETHER OR NOT ARISING FROM THE NEGLIGENCE OF TIX4CAUSE; (III) ANY UNAUTHORIZED ACCESS; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE; (IV) ANY BUGS, VIRUSES, WORMS, DEFECTS OR OTHER ITEMS OF A DESTRUCTIVE NATURE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY; (V) ANY ERROR, MISTAKE, INACCURACY OR OMISSION IN ANY MATERIALS, OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY MATERIALS AVAILABLE THROUGH THE SITE; AND/OR (VI) ANY LOST, STOLEN OR DAMAGED TICKETS. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SITE IS TO STOP USING THE SITE. THE MAXIMUM LIABILITY OF VIVID SEATS, AND ANY OTHER INDEMNIFIED PARTY, AND YOUR SOLE AND EXCLUSIVE REMEDY, FOR ALL DAMAGES, LOSSES SUFFERED BY YOU AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE, SHALL BE THE TOTAL AMOUNT PAID BY YOU, IF ANY, TO ACCESS THE SITE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>
  <p><strong>Arbitration and Dispute Resolution</strong></p>
  <p>You and Tix4cause each agree that any and all disputes, controversies, or claims arising out of or relating to: (i) these Sales Terms; (ii) your use of, or access to, this site; (iii) Tix4Cause’s  services; or (iv) any Proprietary Tickets sold or purchased through this site shall be resolved exclusively through final and binding arbitration rather than in court. The Federal Arbitration Act governs the interpretation and enforcement of this agreement to arbitrate.</p>
  <p>The arbitrator, and not any federal, state, or local court or agency, shall have exclusive authority to resolve any dispute arising out of or relating to the interpretation, applicability, enforceability or formation of this agreement to arbitrate, any part of it, or of these Sales Terms including, but not limited to, any claim that all or any part of this agreement to arbitrate or the Sales Terms is void or voidable.</p>
  <p>If either you or Tix4Cause intends to bring a claim against the other, that party must first send to the other, by certified mail, a completed Intent to Arbitrate Notice ("Intent Notice"). The Intent Notice to Tix4Cause should be sent to Tix 4 Cause, LLC, P.O. Box 4553, Naperville, IL 60667. If you and Tix4Cause are unable to resolve the dispute described in the Intent Notice within thirty (30) days after the Intent Notice is sent, you or Tix4Cause may initiate an arbitration proceeding.</p>
  <p>The arbitration will be conducted by the American Arbitration Association ("AAA") in accordance with its Commercial Arbitration Rules, as modified by this agreement to arbitrate. Exclusive jurisdiction for any such arbitration shall be in Chicago, Illinois. The AAA's rules are available at www.adr.org. A form for initiating arbitration proceedings, Demand for Arbitration, is available on the AAA's website. In addition to filing the Demand for Arbitration with the AAA, in accordance with its rules and procedures, you must send a copy of the completed form to Tix4Cause at the address listed above.</p>
  <p>Payment of all filing, administration and arbitrator fees will be governed by the AAA's rules, unless otherwise stated in this agreement to arbitrate. If the value of the relief sought is $10,000 or less, at your request, Tix4Cause will pay all filing, administrative and arbitrator fees associated with the arbitration. Any request for payment of fees by Tix4Cause should be submitted by mail to the AAA along with the Demand for Arbitration and Tix4Cause will make arrangements to pay all necessary fees directly to the AAA. In the event the arbitrator determines the claim you asserted in the arbitration to be frivolous or brought for an improper purpose, you agree to reimburse Tix4Cause for all fees associated with the arbitration paid by Tix4Cause.
      The arbitrator will decide the substance of all claims in accordance with the laws of the State of Illinois. The arbitrator's award shall be final and binding, and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof.
      </p>
  <p>You can choose to reject this agreement to arbitrate. If you do not wish to be bound by this agreement to arbitrate, you must notify Tix4Cause in writing within thirty (30) days of the date that you first access the site. Your written notification must include your name and address, as well as a clear statement that you do not wish to resolve disputes with Tix4Cause through arbitration. Written notification should be mailed by certified mail to Tix4Cause at the address listed above.</p>
  <p>YOU AND TIX4CAUSE AGREE THAT EACH MAY ONLY BRING CLAIMS AGAINST THE OTHER ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING UNLESS BOTH YOU AND VIVID SEATS ACKNOWLEDGE AND AGREE THAT THE WAIVER IS MATERIAL AND ESSENTIAL TO THE ARBITRATION OF ANY DISPUTES BETWEEN THE PARTIES AND IS NON-SEVERABLE FROM THE AGREEMENT TO ARBITRATE CLAIMS. IF THE WAIVER IS LIMITED, VOIDED OR FOUND UNENFORCEABLE, THEN THE PARTIES' AGREEMENT TO ARBITRATE SHALL BE NULL AND VOID WITH RESPECT TO SUCH PROCEEDING, SUBJECT TO THE RIGHT TO APPEAL THE LIMITATION OR INVALIDATION OF THE WAIVER. UNLESS YOU AND TIX4CAUSE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON'S OR PARTY'S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY'S INDIVIDUAL CLAIMS. ANY RELIEF AWARDED CANNOT AFFECT OTHER VIVID SEATS' USERS.</p>
  <p>Pursuant to 815 ILCS 414/1.5(c), for transactions involving tickets to events in Illinois, You or ticket sellers may elect to submit complaints against one another to the American Arbitration Association ('AAA') under its rules and procedures. The AAA's rules are available at www.adr.org. Such complaints shall be decided by an independent arbitrator in accordance with these Sales Terms and other Terms and Conditions of using this Marketplace. You and ticket sellers also agree to submit to the jurisdiction of the State of Illinois for complaints involving a ticketed event held in Illinois.</p>
  <p><strong>Modification</strong></p>
  <p>Tix4Cause has the right, in its sole discretion, to modify, suspend or discontinue any part of this site at any time, with or without notice.</p>
  <p><strong>Changes in Terms and Conditions</strong></p>
  <p>Tix4Cause reserves the right, in its sole discretion, to change these Sales Terms at any time. If Tix4Cause changes any term or condition, said modification, revision and additional information shall be posted here and shall automatically replace the terms and conditions and become binding on all users of this site. Your continued use of the site following Tix4Cause’s posting of revised terms and conditions constitute your acceptance of the revised agreement.</p>
  <p><strong>Force Majeure</strong></p>
  <p>Tix4Cause shall not be deemed in default or otherwise liable under these Sales Terms due to its inability to perform its obligations by reason of any act of God, fire, earthquake, blizzard, flood, epidemic, accident, explosion, casualty, strike, lockout, labor controversy, riot, civil disturbance, act of public enemy, embargo, war, any law ordinance or regulation, legal order (unless caused by Tix4Cause’s default hereunder), any failure or delay of any transportation, power, or communications system or any other similar cause not under Tix4Cause’s control.</p>
  <p><strong>Allocation of Risk</strong></p>
  <p>You acknowledge and agree that the foregoing disclaimers and limitations of liability represent bargained for allocations of risk and that the pricing and other terms and conditions of this agreement reflect such allocation of risk.</p>
  <p><strong>Additional Provisions</strong></p>
  <p>No agency, partnership, joint venture or other relationship is intended or created by your use of the site.</p>
  <p>These Sales Terms, the use of the Tix4Cause website, and any purchases of Proprietary Tickets hereunder will be governed by the laws of the State of Illinois, without reference to conflict of law principles.</p>
  <p>These Sale Terms contain the entire understanding of the parties with respect to the matters contained herein and supersedes and replaces in its entirety any and all prior communications and contemporaneous agreements and understandings between the parties, whether oral, written, electronic or implied.</p>
  <p>If any provision of these Sales Terms is held invalid or unenforceable under any circumstance, its application in any other circumstances and the remaining provisions shall not be affected. Further, the provision that has been deemed to be invalid or ineffective shall be enforced to the greatest extent permitted by law.</p>
  <p>The heading at the beginning of each paragraph is for reference purposes and no way defines the scope or extent of such paragraph.</p>
</div>
@endsection