@extends('layout')
@section('content')
<div class="legal-header" style="background-image: url({{ asset('img/terms.png') }})">
  <h1>Terms and Conditions</h1>
</div>
<div class="legal-copy container">
    <p>TIX4CAUSE TERMS OF USE</p>

    <p>Effective November 1, 2018</p>
    
    <p>PLEASE READ THESE TERMS OF USE AND THE TERMS AND POLICIES REFERRED TO HEREIN (COLLECTIVELY, &quot;AGREEMENT&quot;) CAREFULLY BEFORE USING THE SERVICES OFFERED BY TIX 4 CAUSE, LLC (&ldquo;TIX4CAUSE&quot;). THE TIX4CAUSE.COM WEBSITE AND DOMAIN NAME, AND ANY OTHER FEATURES, CONTENT, OR APPLICATIONS OFFERED FROM TIME TO TIME BY TIX4CAUSE IN CONNECTION THEREWITH (COLLECTIVELY, &quot;WEBSITE&quot;) ARE OWNED AND OPERATED BY TIX4CAUSE. THE AGREEMENT SETS FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR YOUR USE OF THE WEBSITE. BY USING THE WEBSITE IN ANY MANNER, YOU AGREE TO BE BOUND BY THIS AGREEMENT AND TIX4CAUSE&rsquo;S PRIVACY POLICY POSTED ON THE WEBSITE, WHICH IS INCORPORATED HEREIN BY THIS REFERENCE.</p>
    
    <p>You may at any time request a copy of this Agreement by emailing us at: customersupport@tix4cause.com, Subject: Terms of Use.</p>
    
    <p><strong>1. Modifications of this Agreement.</strong> TIX4CAUSE RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO MODIFY THIS AGREEMENT AT ANY TIME BY POSTING A NOTICE ON THE WEBSITE, OR BY SENDING YOU A NOTICE VIA EMAIL OR POSTAL MAIL. YOU SHALL BE RESPONSIBLE FOR REVIEWING AND BECOMING FAMILIAR WITH ANY SUCH MODIFICATIONS. SUCH MODIFICATIONS ARE EFFECTIVE UPON FIRST POSTING OR NOTIFICATION, AND USE OF THE WEBSITE OR ANY SERVICES BY YOU FOLLOWING SUCH POSTING OR NOTIFICATION CONSTITUTES YOUR ACCEPTANCE OF THE TERMS AND CONDITIONS OF THIS AGREEMENT AS MODIFIED. YOU AGREE TO REVIEW THIS AGREEMENT REGULARLY TO ENSURE THAT YOU ARE UPDATED AS TO ANY CHANGES. THIS AGREEMENT AND ANY OTHER LEGAL NOTICES PUBLISHED BY TIX4CAUSE ON THE WEBSITE, SHALL CONSTITUTE THE ENTIRE AGREEMENT BETWEEN YOU AND TIX4CAUSE CONCERNING THE WEBSITE.</p>
    
    <p><strong>2. Website Access</strong></p>
    
    <p>2.1 Subject to your compliance on a continuing basis with all of the terms and conditions of this Agreement, Tix4Cause hereby grants you permission to use the Website only as set forth in this Agreement, and provided that: (i) you will not copy or distribute any part of the Website in any medium without Tix4ix4cause's prior written authorization; (ii) you will not alter or modify any part of the Website other than as expressly authorized and then only for such express purpose; (iii) you may not circumvent, disable, violate or attempt to violate, or otherwise interfere with the security or integrity of the Website, the proper operation of the Website, the features that prevent or restrict use or copying of any Content (as the term is defined below) or enforce limitations on use of the Website or the Content therein, or interfere with any activity being conducted on the Website; and (iv) you may not decompile, disassemble or reverse engineer any of the software comprising or in any way making up part of the Website.</p>
    
    <p>2.2 In order to access some features of the Website, you may have to create a membership account. You may never use another's account, username or password without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. You must notify Tix4Cause immediately of any breach of security or unauthorized use of your account. You may be required to expressly accept or reject these Terms of Use when you register; you agree that any requirement that you do so does not in any way violate your assent to comply with the Terms of Use. Although Tix4Cause will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Tix4Cause or others due to such unauthorized use.</p>
    
    <p>2.3 You agree not to use or launch any automated system, including without limitation, &quot;robots,&quot; &quot;spiders,&quot; or &quot;offline readers,&quot; that accesses the Website in a manner that sends more request messages to Tix4Cause&rsquo;s servers in a given period of time than a single human can reasonably produce in the same period by using a conventional web browser. Tix4Cause reserves the right in its sole discretion to block access or discontinue services to offenders, and to investigate and take appropriate legal action against anyone who, in Tix4Cause 's sole discretion, violates this provision, including without limitation, reporting you to law enforcement authorities.</p>
    
    <p><strong>3. Tix4Cause Services</strong></p>
    
    <p>3.1 The sale and purchase of all donated and event tickets as well as certificates on the Website is subject to the Tix4Cause Online Sales Terms; provided, however, that purchase of event tickets issued by ticketnetwork.com is subject to the Ticket Network Sales Terms.</p>
    
    <p>3.2 Entities may elect to be included in the Website&rsquo;s list of member causes, subject to the Tix4Cause Charity Membership Terms.</p>
    
    <p>3.3 If and when applicable, the sale and purchase of vouchers on the Website is subject to the Tix4Cause Cause Marketing Terms and Conditions.</p>
    
    <p><strong>4. Intellectual Property Rights.</strong> The content on the Website, including without limitation, the text, software, scripts, graphics, files, images, photos, sounds, music, videos, interactive features and the like (collectively &quot;Content&quot;) and the trademarks, service marks and logos contained therein (&quot;Marks&quot;), are owned by or licensed to Tix4Cause, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. Tix4Cause reserves all rights not expressly granted in and to the Website and the Content. You agree to not use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any other purposes whatsoever any Content, including, but not limited to, image, audio, and visual content, Marks, or other proprietary rights not owned by you, (i) without the express prior written consent of the respective owners, or (ii) in any way that violates any right of any third party. If you download or print a copy of the Content for personal use, you must retain all copyright and other proprietary notices contained therein.</p>
    
    <p><strong>5. Term.</strong> This Agreement shall remain in full force and effect while you use the Website. You may terminate your use of the Website or your membership at any time by emailing customersupport@tix4cause.com. Tix4Cause may terminate your access to the Website or your membership at any time, for any reason, and without warning. Sections 4 and 7 through 14 shall survive termination or expiration of this Agreement for any reason.</p>
    
    <p><strong>6. Fees; Tickets; Certificates; Tax Treatment Disclaimer</strong></p>
    
    <p>6.1 Tix4Cause may charge fees for all or some of the Website&rsquo;s services in its sole discretion. If Tix4Cause terminates your registration or membership because of your breach of the Agreement, you will not be entitled to a refund of any unused portion of such fees, except to the extent required under applicable law. Billing for monthly fees is recurrent, so you should state your wish to cancel your subscription at least 72 hours before it is set to renew.</p>
    
    <p>6.2 Tix4Cause offers a service for Website members to purchase tickets or donate tickets to various events to various cause members, as well as to purchase various certificates by means of the Website, subject to the Tix4Cause Online Sale Terms. Ticket and certificate descriptions, prices and other information on the Website may contain typographical errors or may be incorrect, incomplete or not current. Tix4Cause does not monitor or control ticket or certificate offerings on the Website and shall incur no liability in connection therewith. Tix4Cause and its partners make no representation as to whether all or any portion of the value of the tickets donated to charities via the Website is tax deductible. Please consult with your tax advisor to determine whether a deduction of any portion of such amount is allowable. Tix4Cause shall have no liability for any claim by any federal or state tax authority with respect to your characterization of this transaction on your federal and state tax returns.</p>
    
    <p><strong>7. Third-Party Websites.</strong> The Website may contain links to third party websites that are not owned or controlled by Tix4Cause. When you access third-party websites, you do so at your own risk. Tix4Cause encourages you to be aware when you leave the Website and to read the terms and conditions and privacy policy of each third party website that you visit. Tix4Cause has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of, or opinions expressed in any third-party websites. In addition, Tix4Cause will not and cannot monitor, verify, censor or edit the content of any third-party website. By using the Website, you expressly relieve Tix4Cause from any and all liability arising from your use of any third party website.</p>
    
    <p><strong>8. WARRANTY DISCLAIMER.</strong> TO THE FULLEST EXTENT PERMITTED BY LAW, TIX4CAUSE, ITS SUPPLIERS, LICENSORS, AND PARTNERS, AND EACH OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND YOUR USE THEREOF, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, NEITHER tix4cause NOR ITS SUPPLIERS NOR LICENSORS, NOR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS, MAKES ANY WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE WEBSITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THE WEBSITE, AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE WEBSITE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF THE SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE WEBSITE BY ANY THIRD PARTY; AND/ OR (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE WEBSITE. TIX4CAUSE DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY CONTENT, PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE WEBSITE OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY ADVERTISING, AND tix4cause WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF CONTENT, PRODUCTS OR SERVICES. THE WEBSITE IS CONTROLLED AND OFFERED BY TIX4CAUSE FROM ITS FACILITIES IN THE UNITED STATES OF AMERICA. TIX4CAUSE MAKES NO REPRESENTATIONS THAT THE WEBSITE IS APPROPRIATE OR AVAILABLE FOR USE IN OTHER LOCATIONS. THOSE WHO ACCESS OR USE THE WEBSITE FROM OTHER JURISDICTIONS ARE RESPONSIBLE FOR COMPLIANCE WITH LOCAL LAW.</p>
    
    <p><strong>9. Indemnity.</strong> You agree to defend, indemnify and hold harmless Tix4Cause, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, demands, and expenses (including but not limited to, attorneys' fees) arising from: (i) your use of and access to the Website or any Content that you post thereon; (ii) your violation of any term of this Agreement or of your representations and warranties set forth herein; or (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right. </p>
    
    <p><strong>10. Eligibility.</strong> By using the Website, you represent and warrant that (i) all registration information you submit is accurate and truthful; (ii) you will maintain the accuracy of such information; (iii) you are 18 years of age or older (if you are agreeing to these terms and conditions on behalf of a minor, you certify to Tix4Cause that you are such minor&rsquo;s legal guardian); and (iv) your use of the Website does not violate any applicable law or regulation. Your membership may be terminated without warning if tix4cause believes that you are under 18 years of age and that your legal guardian did not authorize your Website membership. </p>
    
    <p><strong>11. LIMITATION OF LIABILITY.</strong> IN NO EVENT SHALL TIX4CAUSE, ITS SUPPLIERS, LICENSORS, CHARITY PARTNERS, OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING LOST PROFITS, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT TIX4CAUSE IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. SUBJECT TO THE FOREGOING, TIX4CAUSE'S LIABILITY TO YOU FOR ANY REASON, WILL BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO TIX4CAUSE FOR SERVICES IN CONNECTION WITH THE WEBSITE.   YOU SPECIFICALLY ACKNOWLEDGE THAT TIX4CAUSE SHALL NOT BE LIABLE FOR THE DEFAMATORY, OFFENSIVE, FRAUDULENT, DECEPTIVE OR ILLEGAL CONDUCT OF ANY THIRD PARTY, INCLUDING, WITHOUT LIMITATION, TICKET SELLERS OR CHARITIES, AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS SOLELY AND ENTIRELY WITH YOU.</p>
    
    <p><strong>12. Assignment.</strong> You may not transfer or assign this Agreement or any rights and licenses granted hereunder without Tix4Cause's prior written consent. Tix4Cause may freely transfer, assign, or delegate this Agreement, and any of its rights or obligations hereunder.</p>
    
    <p><strong>13. U.S. Export Controls.</strong> Any software available in connection with the Website is further subject to United States export controls. No software may be downloaded from the Website or otherwise exported or re-exported in violation of U.S. export laws. Downloading or using the software is at your sole risk.</p>
    
    <p><strong>14. Miscellaneous.</strong> If there is any dispute about or involving the Website, you agree that the dispute shall be governed by the laws of the State of Illinois, without regard to conflict of laws provisions thereof. Any dispute arising from or relating to the subject matter of this Agreement shall be finally settled by arbitration in Chicago, Illinois, using the English language in accordance with the Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. (&quot;JAMS&quot;) then in effect, by one commercial arbitrator(s) with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with the Arbitration Rules and Procedures of JAMS. Any arbitrator so selected shall have substantial experience in the media industry. The arbitrator shall have the authority to grant specific performance and to allocate between the parties the costs of arbitration (including service fees, arbitrator fees and all other fees related to the arbitration) in such equitable manner as the arbitrator may determine. The prevailing party in the arbitration shall be entitled to receive reimbursement of its reasonable expenses (including reasonable attorneys' fees, expert witness fees and all other expenses) incurred in connection therewith. Judgment upon the award so rendered may be entered in a court having jurisdiction or application may be made to such court for judicial acceptance of any award and an order of enforcement, as the case may be. Notwithstanding the foregoing, each party shall have the right to institute an action in a court of proper jurisdiction for preliminary injunctive relief pending a final decision by the arbitrator. For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in the United States Federal Courts located in Chicago, Illinois. If any provision of this Agreement is deemed invalid or unenforceable by a court of competent jurisdiction, the invalidity or unenforceability of such provision shall not affect the validity or enforceability of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and tix4cause's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND TIX4CAUSE AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE WEBSITE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.  </p>
</div>
@endsection